plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.maven.publish)
}

group = 'com.bmit.lib_core'
version = '1.0.0'

android {
    namespace 'com.bmit.lib_core'
    compileSdk 34

    defaultConfig {
        minSdk 30
        targetSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

// jitpack方式
afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release // 打包 release 变体

                // 2. 显式指定 artifactId 为你的子模块名字
                artifactId = 'lib_core'
            }
        }
    }
}



//maven托管方式
//publishing {
//    publications {
//        release(MavenPublication) {
//            groupId = 'com.bmit.lib_core'
//            artifactId = 'bt'
//            version = '1.0.0'
//
//            afterEvaluate {
//                from components.release
//            }
//        }
//    }
//
//    repositories {
//        maven {
//            name = 'GitHubPackages'
//
//            url = uri(
//                    'https://maven.pkg.github.com/HuaiJunHu/BaseApp'
//            )
//
//            credentials {
//                username = providers.gradleProperty('gpr.user').orNull
//                password = providers.gradleProperty('gpr.key').orNull
//            }
//        }
//    }
//}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.androidx.viewbinding
    implementation libs.material
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.activity.ktx
    implementation libs.fragment.ktx
    implementation libs.constraintlayout

    compileOnly files('libs/framework.jar')

    testImplementation libs.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit
}